### ISSUE TITLE
smaller batch sizes

### ISSUE THREAD

**Issue by invoxiaehu** [tlkh/tf-metal-experiments#11]
Thank you !
Because of unified memory, I wonder if tensorflow training on M1 max would be less badly impacted by smaller batch sizes, than training on the RTX 3090...
I would love to have the comparisons of resnet and mobilenet for batchsize=16, on M1 max and RTX 3090.

**Comment by tlkh** [comment]
At batch size 16 for ResNet50:

* M1 Max: 118
* 3090: 583 (XLA+FP16), 381 (FP32)

<img width="658" alt="Screenshot 2021-11-19 at 19 54 32" src="https://user-images.githubusercontent.com/5409617/142618909-dd3fb531-bdc3-4c13-bcca-6be8247c19a1.png">

**Comment by tlkh** [comment]
FYI: I do not think unified memory works in TensorFlow, maybe because it needs to convert CPU TensorFlow tensor to Metal tensor and run on the GPU.

I tested, and tensor created on CPU has slow read speed from GPU, and vice versa, so you still need to copy tensor like a normal system.

**Comment by invoxiaehu** [comment]
ok thanks a lot ! Very interesting. Hope further optimizations for the M1 family will come.
