### ISSUE TITLE
M1 Max Thermal Throttling

### ISSUE THREAD

**Issue by yadamonk** [tlkh/tf-metal-experiments#4]
Hi @tlkh

Thank you so much for creating and running those benchmarks. I would be interested if thermal throttling affects training speed (```ms/step```) after a few minutes.

Could you share your training logs when running e.g. ```bm_rn50.py``` for ```benchmark_epochs = 20```?

**Comment by yadamonk** [comment]
Just out of curiosity, what happens when you run the M1 Max in _low_ power mode. I'm especially interested in the power consumption of the GPU and the score you get for `bm_rn50.py`.

**Comment by yadamonk** [comment]
The background for my question is that I'm wondering if _low_ power mode might be an option for longer training runs e.g. over night.

**Comment by tlkh** [comment]
Sorry, recently I bit more occupied with other stuff, I plan to circle back and test it later this week

**Comment by yadamonk** [comment]
Today I finally got my M1 Max and I'm happy to report that for the `resnet50` benchmark _low power_ mode achieves 61.4% of the performance you reported with an average GPU power consumption of only 15 Watts (total package power is around 30).

Needless to say the machine stays cool as a cucumber even when training for longer which is really important to me as it's my primary computer.

<img width="1296" alt="Screenshot 2021-11-17 at 21 38 05" src="https://user-images.githubusercontent.com/83785060/142279240-efc8f71e-4d0e-4c23-89c0-f248564582fc.png">
