### ISSUE TITLE
adding A100, other configs comparison for fun

### ISSUE THREAD

**Issue by ngam** [tlkh/tf-metal-experiments#6]
Summary tables (more details below and in comments):
| Model | M1 7c  |  M1 32c | A 100 (-) |  V 100 (-) | P 100 (-) | T4 (-) | K 80 (-) | Q P 5000 (-) | Q M 4000 (-) | Q RTX 4000 (-) |
| --- | --- | --- | ---| --- |  --- | --- | --- | --- | --- | --- |
| RN50 |  10 |  135 |  611 | 347 | 211 | 134 | F | 131 | F | F | 
| MNV2 | 23 | 352 |  269 | 187 | 125 | 193 | 94 | 181 | F | F | 
| DBERT | 15 | 120 |  761 | 187 | 149 | 94 | 47 | 109 | 39 | 129 | 
| BERTL | 1 | 18 |  136 | 31 | 16 | 15 | 4 | 17 | F | F | 

| Model | M1 7c  |  M1 32c | A 100 (+) | V 100 (+) | P 100 (+) | T4 (+) | K 80 (+) | Q P 5000 (+) | Q M 4000 (+) | Q RTX 4000 (+) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |  
| RN50 |  10 |  135 |  1147 | v100 | 252 | na | na | na | na | na |
| MNV2 | 23 | 352 | 1870 | v100 |  128 | na | na | na | na | na |
| DBERT | 15 | 120 | 1909 | v100 | 209 | na | na | na | na | na |
| BERTL | 1 | 18 | 309 | v100 | 23 | na | na | na | na | na |

---
---
---
---
---
Really good and useful work here --- thank you! I can potentially fill the remaining values if you think this would be of interest. Note: I simply copied-pasted the content of your .py files and ran them in a notebook. Also note: accuracy will improve by using float32 as op indicates M1 can only use float32, hence comparison should be without optimization imo. RTX 3090 and A100 are somewhat similar in my understanding in terms if benchmarks like these fwiw.

--- 
M1 on MBA (7-core, 8GB RAM). Completely froze my laptop! Even the trackpad stopped responding... first time ever I notice I have this slowdown/lag happens on this MBa, but results incoming! Obviously it's taking forever...

| Model            | GPU        | BatchSize | Throughput  | Power | Memory |
| -----------    | ---------- | --------- | ----------- | ----- | ------ |
| ResNet50       | M1 7c | 64        | 10.3 img/sec | ?   | ?  |
| MobileNetV2  | M1 7c | 128       | 22.7 img/sec | ?  | ?  |
| DistilBERT      | M1 7c | 64        | 15.2 seq/sec | ?   | ?   |
| BERTLarge     | M1 7c | 32        | 0.6 seq/sec  | ?   | ?  |

---
with optimization:

| Model       | GPU        | BatchSize | Throughput  | Power | Memory |
| ----------- | ---------- | --------- | ----------- | ----- | ------ |
| ResNet50    | A100 40GB | 64        | 1147.4 img/sec | ?   | ?  |
| MobileNetV2 | A100 40GB | 128       | 1869.7 img/sec | ?  | ?  |
| DistilBERT  | A100 40GB | 64        | 1909.3 seq/sec | ?   | ?   |
| BERTLarge   | A100 40GB | 32        | 309.3 seq/sec  | ?   | ?  |

---
without optimziation:

| Model       | GPU        | BatchSize | Throughput  | Power | Memory |
| ----------- | ---------- | --------- | ----------- | ----- | ------ |
| ResNet50    | A100 40GB | 64        | 610.8 img/sec | ?   | ?  |
| MobileNetV2 | A100 40GB | 128       | 269.4 img/sec | ?  | ?  |
| DistilBERT  | A100 40GB | 64        | 761.1 seq/sec | ?   | ?   |
| BERTLarge   | A100 40GB | 32        | 135.5 seq/sec  | ?   | ?  |

---

| Model       | GPU        | BatchSize | Throughput  | Power | Memory |
| ----------- | ---------- | --------- | ----------- | ----- | ------ |
| ResNet50    | M1 Max 32c | 64        | 135 img/sec | 40W   | 13 GB  |
| MobileNetV2 | M1 Max 32c | 128       | 352 img/sec | 37W   | 15 GB  |
| DistilBERT  | M1 Max 32c | 64        | 120 seq/sec | 35W   | 9 GB   |
| BERTLarge   | M1 Max 32c | 32        | 18 seq/sec  | 36W   | 14 GB  |

---

| Model       | GPU        | BatchSize | Throughput  | Power |
| ----------- | ---------- | --------- | ----------- | ----- |
| ResNet50    | 3090       | 64        | 957 img/sec | 300W  |
| MobileNetV2 | 3090       | 128       | 1927 img/sec| 310W  |
| DistilBERT  | 3090       | 64        | 1040 seq/sec| 310W  |
| BERTLarge   | 3090       | 32        | 164 seq/sec | 320W  |

---

**Comment by ngam** [comment]
> Also, and this might surprise you: I haven’t heard my fans yet! (even with high power mode) I’m actually wondering why these chips aren’t allowed to clock higher.

@SubaruSpirit + @tlkh 

I got my MBP14inch2021 (M1 Max, 64 GB, 1 TB). Sad to report, the fans do turn on pretty quickly with the tests in this repo. Results are in line with what's published in this issue and in the main readme, ~5--10% lower, I'd say. The fans are not as noisy as the Intel versions; and the laptop isn't as hot. However, if fan noise is an issue for you, the M1 Air has no fans! Having said that, the noise is easy to miss --- the fans are very quiet even when they are on. 

In my opinion, besides the display and potentially pro video editing, M1 Air is more or less the same. This MBP does offer a little bit of extra smoothness and it goes well with the extra smooth display. Is it worth 4x the M1 Air though? That'd be the question for you to answer 🤞

**Comment by tlkh** [comment]
Seems roughly in line with reviews, the 14 inch model definitely has poorer cooling! Glad you’re enjoying your new MacBook!

**Comment by ngam** [comment]
@tlkh closing this, but feel free to copy/edit the values, etc. 👍
